name: Frontend CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build
      env:
        REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      run: npm run build

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      env:
        IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/anime-frontend
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker push $IMAGE_NAME:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy anime-frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/anime-frontend:${{ github.sha }} \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated